# Generated by Django 5.2.3 on 2025-07-11 07:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international phone number.', regex='^\\+?\\d{7,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('cold_call', 'Cold Call'), ('linkedin', 'LinkedIn'), ('email_campaign', 'Email Campaign'), ('other', 'Other')], default='other', max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('web_dev', 'Web Development'), ('mobile_dev', 'Mobile Development'), ('automated_testing', 'Automated Testing'), ('social_media_auto', 'Social Media Automation'), ('ecommerce_auto', 'E-commerce Automation')], default='web_dev', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=100)),
                ('monthly_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('one_time_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('short_description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('web_dev', 'Web Development'), ('mobile_dev', 'Mobile Development'), ('automated_testing', 'Automated Testing'), ('social_media_auto', 'Social Media Automation'), ('ecommerce_auto', 'E-commerce Automation')], default='web_dev', max_length=50)),
                ('client_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_info', to='common.lead')),
            ],
        ),
    ]
