# Generated by Django 5.2.3 on 2025-07-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_subscribed', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('mobile_dev', 'Mobile Development'), ('automated_testing', 'Automated Testing'), ('social_media_auto', 'Social Media Automation'), ('ecommerce_auto', 'E-commerce Automation'), ('sales_auto', 'Sales Automation')], default='web_dev', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('mobile_dev', 'Mobile Development'), ('automated_testing', 'Automated Testing'), ('social_media_auto', 'Social Media Automation'), ('ecommerce_auto', 'E-commerce Automation'), ('sales_auto', 'Sales Automation')], default='web_dev', max_length=50),
        ),
    ]
